name: Jekyll Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
   
    runs-on: ubuntu-22.04
    
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3

      - name: Bundler Cache
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Validate JSON files
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"

     
      - name: Build Site
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential zlib1g-dev
          gem install bundler
          bundle install
          JEKYLL_ENV=production bundle exec jekyll build

      - name: Build & Deploy to GitHub Pages
        uses: joshlarsen/jekyll4-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
